### ISSUE TITLE
Entité-relation ou Entité-association

### ISSUE THREAD

**Issue by Rodriguevb** [titouanc/db-synthese#1]
Salut,

Apparemment vous avez traduit "Entity-Relationship" du cours en "Entité-Relation". Seulement au TP et à l'examen il parle de "Entité-Association (EA)".

Ça peut paraître débile comme ça mais j'ai moi-même un peu bugé en pensant que c'était un nouveau concept différent que je connaissais pas, peut être que ca risque d'en perturber d'autres.. ;)

Et tout ceci se trouve dans la section "Modèle relationnel" traduit par le professeur plutot que "Modèle entité-relation" !

**Comment by titouanc** [comment]
Cette partie a été rédigée en lisant les slides, et l'acronyme **ER** est utilisé partout, y'a pas vraiment d'autre raison à cette notation dans la synthèse. Hésite pas à proposer une PR si tu veux changer ça

**Comment by Rodriguevb** [comment]
C'est proposé. Oui je sais sur les slides. Mais à l'examen c'est une autre traduction qui est utilisée par le prof. Après tu fais ce que tu veux, c'était juste une indication ;)

**Comment by titouanc** [comment]
Je vais rajouter une note dans l'intro à ce sujet
