### ISSUE TITLE
Phrase incomplète/oubli

### ISSUE THREAD

**Issue by Rodriguevb** [titouanc/db-synthese#2]
Au point 2.6.1 Suppression des généralisations : 

"Traduction des entités et relations en tables les attributs deviennent des colonnes, faire attention
aux attributs multivalués, les entité fortes et faibles. Les relations doivent se traduire par des"

La phrase est incomplète :)

Merci!

**Comment by titouanc** [comment]
C'était en cours de rédaction, normalement ça vient d'être changé
